services:
  db:
    image: postgres:16-alpine
    container_name: payroll_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env

    environment:
      - POSTGRES_HOST=db

    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      - db
volumes:

  postgres_data:

